"""add YT socialnetwork enum

Revision ID: 0dfbe6bf12ac
Revises: efa447f380a2
Create Date: 2024-07-05 21:59:05.248817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfbe6bf12ac'
down_revision: Union[str, None] = 'efa447f380a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE socialnetworksenum ADD VALUE 'YT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
