"""add type field

Revision ID: 655b4eadcbd1
Revises: 83681ed9ce63
Create Date: 2024-06-26 16:30:22.788463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655b4eadcbd1'
down_revision: Union[str, None] = '83681ed9ce63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type')
    # ### end Alembic commands ###
