"""change type of author and resource fields

Revision ID: 87c3c241dd82
Revises: 0dfbe6bf12ac
Create Date: 2024-07-05 23:00:05.259047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c3c241dd82'
down_revision: Union[str, None] = '0dfbe6bf12ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('post', 'resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'resource_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('post', 'author_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
