"""add unique couple of fields

Revision ID: d58f956d9630
Revises: fcfa2d0f35b6
Create Date: 2024-06-28 13:37:45.655150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58f956d9630'
down_revision: Union[str, None] = 'fcfa2d0f35b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_publication', 'post', ['author_vk_id', 'resource_vk_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_publication', 'post', type_='unique')
    # ### end Alembic commands ###
