"""add nickname field

Revision ID: efa447f380a2
Revises: 0be753361b4b
Create Date: 2024-07-05 17:54:02.733685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa447f380a2'
down_revision: Union[str, None] = '0be753361b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('nickname', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'nickname')
    # ### end Alembic commands ###
