"""replace author&link with vk_id fields

Revision ID: fcfa2d0f35b6
Revises: f81271075de1
Create Date: 2024-06-28 13:32:58.359997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfa2d0f35b6'
down_revision: Union[str, None] = 'f81271075de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_vk_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('resource_vk_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_link_key', 'post', type_='unique')
    op.drop_column('post', 'author')
    op.drop_column('post', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('link', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('post', sa.Column('author', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('post_link_key', 'post', ['link'])
    op.drop_column('post', 'resource_vk_id')
    op.drop_column('post', 'author_vk_id')
    # ### end Alembic commands ###
